import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Logo } from '../components/Logo';
import { useAuth } from '../context/AuthContext';
import { trackReportViewed } from '../lib/recentViewed';
import { getReport } from '../lib/swaStewaApi';

export function PublicReportViewPage() {
  const { reportNumber } = useParams<{ reportNumber: string }>();
  const { user } = useAuth();
  const [loading, setLoading] = useState(true);
  const [valid, setValid] = useState(false);
  const [verified, setVerified] = useState(false);
  const [pdfUrl, setPdfUrl] = useState('');
  const [report, setReport] = useState<Record<string, unknown> | null>(null);

  useEffect(() => {
    if (!reportNumber) return;
    getReport(reportNumber)
      .then((res) => {
        setValid(res.valid !== false);
        setVerified(!!res.verified);
        setPdfUrl(res.pdf_url ?? '');
        setReport(res.report as unknown as Record<string, unknown>);
        const id = (res.report as { id?: number } | undefined)?.id;
        if (typeof id === 'number') trackReportViewed(id);
      })
      .catch(() => setValid(false))
      .finally(() => setLoading(false));
  }, [reportNumber]);

  if (loading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-surface">
        <p className="text-text-muted">Loading report…</p>
      </div>
    );
  }

  if (!valid || !report) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-surface p-6">
        <div className="w-full max-w-md rounded-3xl border border-red-200 bg-card p-8 text-center shadow-xl">
          <Logo />
          <p className="mt-6 text-2xl font-bold text-red-600">✗ INVALID REPORT</p>
          <p className="mt-2 text-text-muted">Record Not Found</p>
          <Link to="/" className="mt-6 inline-block text-sm text-primary underline">
            Return to home
          </Link>
        </div>
      </div>
    );
  }

  const data = (report.report_data ?? {}) as Record<string, string>;
  const status = String(report.status ?? '');
  const backTo = user ? '/reports' : '/';
  const backLabel = user ? 'Reports Hub' : 'Return to home';

  return (
    <div className="min-h-screen bg-surface">
      <header className="border-b border-border bg-card px-6 py-4">
        <Logo size="sm" />
      </header>

      <div className="mx-auto max-w-4xl px-6 py-8">
        <Link
          to={backTo}
          className="mb-6 inline-flex items-center gap-2 rounded-xl border border-border bg-card px-4 py-2.5 text-base font-semibold text-text shadow-sm transition hover:border-primary/50 hover:bg-primary-light hover:text-primary"
        >
          <span aria-hidden className="text-lg leading-none">←</span>
          {backLabel}
        </Link>

        <div
          className={`mb-6 rounded-2xl p-4 text-center ${
            verified ? 'bg-primary-light text-primary' : 'bg-warning-bg text-warning'
          }`}
        >
          <p className="text-lg font-bold">
            {verified ? '✓ VERIFIED OFFICIAL REPORT' : 'Report pending verification'}
          </p>
          <p className="text-sm">Generated by the Project Monitoring System</p>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          <section className="rounded-2xl border border-border bg-card p-5 shadow-sm">
            <h2 className="font-semibold text-text">Project information</h2>
            <dl className="mt-3 space-y-2 text-sm">
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Project name</dt>
                <dd className="text-right font-medium">{data.project_name}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Location</dt>
                <dd>{data.location}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Contractor</dt>
                <dd>{data.contractor}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Contract amount</dt>
                <dd>{data.contract_amount}</dd>
              </div>
            </dl>
          </section>

          <section className="rounded-2xl border border-border bg-card p-5 shadow-sm">
            <h2 className="font-semibold text-text">Report information</h2>
            <dl className="mt-3 space-y-2 text-sm">
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Report number</dt>
                <dd className="font-mono font-medium">{String(report.report_number)}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Report type</dt>
                <dd>{String(report.report_type)}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Date generated</dt>
                <dd>{report.generated_at ? String(report.generated_at).slice(0, 10) : '—'}</dd>
              </div>
              <div className="flex justify-between gap-4">
                <dt className="text-text-muted">Status</dt>
                <dd className="capitalize">{status.replace('_', ' ')}</dd>
              </div>
            </dl>
          </section>
        </div>

        {pdfUrl && (
          <section className="mt-8 rounded-2xl border border-border bg-card p-5 shadow-sm">
            <div className="mb-4 flex flex-wrap gap-3">
              <a
                href={pdfUrl}
                download
                className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary-dark"
              >
                Download PDF
              </a>
              <button
                type="button"
                onClick={() => window.open(pdfUrl, '_blank')?.print()}
                className="rounded-xl border border-border px-4 py-2 text-sm font-medium hover:bg-surface-muted"
              >
                Print PDF
              </button>
            </div>
            <iframe
              title="Official PDF"
              src={pdfUrl}
              className="h-[70vh] w-full rounded-xl border border-border"
            />
          </section>
        )}

        {!pdfUrl && verified === false && (
          <p className="mt-6 text-center text-sm text-text-muted">
            Official PDF is available after approval.
          </p>
        )}
      </div>
    </div>
  );
}
